# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(default='/static/polls/images/background.gif', upload_to='/static/polls/images/'),
        ),
    ]
