# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20161004_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='productimage',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='productimage',
            name='price_in_dollars',
            field=models.DecimalField(decimal_places=2, default='0000', max_digits=6),
        ),
        migrations.AddField(
            model_name='productimage',
            name='slug',
            field=models.SlugField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_image',
            field=models.ImageField(default='/static/polls/images/background.gif', upload_to='polls/static/polls/images/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.ImageField(default='/static/polls/images/background.gif', upload_to='polls/static/polls/images/'),
        ),
    ]
