# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20161019_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='price_in_dollars',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
    ]
